version: '3.9'

services:
  backend:
    build: .
    command: bash scripts/run.sh
    volumes:
      - .:/adv
    env_file:
      - .env.template
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=adv_user
      - POSTGRES_PASSWORD=adv_password
      - POSTGRES_DB=adv_db

networks:
  default:
    external: true
    name: external-network

volumes:
  postgres_data:
